export enum RaffleStatus {
	PENDING = "PENDING",
	ONGOING = "ONGOING",
	CLOSED = "CLOSED",
	DRAWN = "DRAWN",
	WINNER_CONFIRMED = "WINNER_CONFIRMED",
	CANCELED = "CANCELED",
	FINISHED = "FINISHED",
	SORTABLE = "SORTABLE",
}
