export enum RaffleStatus {
	PENDING = "PENDING",
	ONGOING = "ONGOING",
	CLOSED = "CLOSED",
	DRAWN = "DRAWN",
	WINNER_CONFIRMED = "WINNER_CONFIRMED",
	CANCELED = "CANCELED",
	UNDER_REVIEW = "UNDER_REVIEW",
	PRIZE_DELIVERED = "PRIZE_DELIVERED",
}
